### ISSUE TITLE
Products in cart after login

### ISSUE THREAD

**Issue by vitorargosm** [mobiloudsupport/mobiloud-commerce#4]
We have a problem with the way the cart behaves after the user logs in.

Imagine the following situation:

1. The user adds 3 products to the cart
2. During checkout he is asked to log in
3. After logging in the cart updates and the 3 initial products are no longer in the cart, instead, the user has the latest products he added to his cart while logged in.

Can we find a way to resolve this? The best option, I believe, would be to replace whatever the user had in his cart with the most recent products he added to the cart.

**Comment by mobiloudsupport** [comment]
Closing for now as this seems to be a problem on the app side
