### ISSUE TITLE
Add CSS editor for commerce endpoints

### ISSUE THREAD

**Issue by mobiloudsupport** [mobiloudsupport/mobiloud-commerce#9]
@mobiloud-sid 

Can we implement a CSS editor for the commerce pages? The CSS code added to it should be applied to all commerce endpoints, such as:

- [x] Single product
- [x] Lists of products
- [x] Categories
- [x] Cart
- [x] Checkout
- [x] Account

It should work like the CSS editor we have under "Editor" at the moment.

Let me know if there are any concerns with implementing this.

**Comment by mobiloud-sid** [comment]
Added in 6bbe99

**Comment by mobiloudsupport** [comment]
@mobiloud-sid I have tested this, but I found the implementation to be a bit confusing.

Could we instead create a new entry in the existing "Code editor" that says "Commerce Custom CSS"? Just a single entry that applies to all commerce endpoints.

**Comment by mobiloud-sid** [comment]
> @mobiloud-sid I have tested this, but I found the implementation to be a bit confusing.
> 
> Could we instead create a new entry in the existing "Code editor" that says "Commerce Custom CSS"? Just a single entry that applies to all commerce endpoints.

Fixed here - 2398100f84694cfa70f9d9d2b59ff6acede1cc06
